### ISSUE TITLE
Entering/Scanning VIN Numbers

### ISSUE THREAD

**Issue by kgilliam3662** [ConceptualSystems/sms-mobile-portable#10]
When using a scanner or camera to capture a VIN# from a vehicle, I have found some vehicles
return a VIN# that is 18 chars long.  Ex:  Nissan Titan 2010 returns I1N6AA0ED4AN318993
the leading "I" will cause the Decode operation to fail.  If you remove the leading "I" then the Decode operation will succeed.  Therefore, if the VIN# is 18 chars long, remove the leading chars not matter what it is.

**Comment by moonlightcheese** [comment]
I added this check both in the dialog, so it trims before setting the text field and added it also to the VIN decoder so that even if someone enters a long VIN manually it will still trim the leading characters if it's greater than 17 characters in length.

**Comment by kgilliam3662** [comment]
Thank you!

Keith
