### ISSUE TITLE
Dropbox integration for image storage

### ISSUE THREAD

**Issue by moonlightcheese** [ConceptualSystems/sms-mobile-portable#12]
Rather than use Tomcat, we want to shift to using Dropbox for storing images for ease of use.

**Comment by moonlightcheese** [comment]
Dropbox account limit seems to have been reached.
Need to make a separate account and see if it will connect to SMS Mobile.  If not, then need to contact Dropbox about user limit.

**Comment by kgilliam3662** [comment]
installed SMSMobile 1.52 and verified settings.  click Dropbox Account and signed into my dropbox
account and it worked this time.

**Comment by moonlightcheese** [comment]
Completed in SMS Mobile 1.52.
