### ISSUE TITLE
GetWeight & FloorScaleTicket Messages NOT FIXED!

### ISSUE THREAD

**Issue by kgilliam3662** [ConceptualSystems/sms-mobile-portable#16]
reopen, This is still not fixed. no grossnapshot images are sent back to SMSMDS during Transmit.

I understand that you like to create a single library for all you message, but I believe you need to break this one apart. Review Ticket has nothing to do with New Floor Scale message.

I need this fixed asap. My customers are upset, they are losing images that they need now.

Please do more testing before closing!   

The Win7 test machine is dead, so I will be rerouting your SMSMDS 3005 messages to my computer.  i'll send you txt msg with username/password for SMSMobile.  this database has a very limited set of products.

**Comment by moonlightcheese** [comment]
Fixed in SMS Mobile 1.54.
